# Site settings
title: Freedom To Go
tagline: Itâ€™s our future. How will we go?
description: > # ignore newlines
  Description
# email: 

baseurl: "/FreedomToGO"
url: "http://commbocc.github.io"
# paginate: 10
# paginate_path: "posts/:num"

# Build settings
markdown: kramdown
permalink: pretty
